export const CategoriesDetails = [
    { id: "ac", value: "ac", link: "/category/ac", image: "Ac.jpg" },
    { id: "painting", value: "painting", link: "/category/painting" , image: "painting.jpg" },
    { id: "plumbing", value: "plumbing", link: "/category/plumbing" , image: "plumbing.jpg" },
    { id: "electrical", value: "electrical", link: "/category/electrical", image: "electrical.jpg" },
    { id: "deepcleaning", value: "deep cleaning", link: "/category/deepcleaning", image: "cleaning1.jpg" },
    { id: "woodwork", value: "woodwork", link: "/category/woodwork/service/custom-wood-job"  ,image: "wood.jpg"  },
    { id: "handyman", value: "handyman", link: "/category/handyman"  , image: "cleaning.jpg" },
    { id: "parttimemaids", value: "part time maids", link: "/category/parttimemaids/service/maids" , image: "maid.jpg"  },
    { id: "sofadeepshampoo", value: "sofa deep shampoo", link: "/category/sofadeepshampoo/service/custom-sofa-job", image: "sofa.jpg" },
    { id: "grinding", value: "grinding", link: "/category/grinding/service/custom-grinding-job"   },
    { id: "glasswork", value: "glasswork", link: "/category/glasswork" ,image: "glass.jpg"  },
    { id: "ac-soft-service", value: "ac soft service", link: "/category/ac/service/ac-soft-service" , image: "Ac.jpg" },
    { id: "ac-repair-maintainance", value: "ac repair and maintainance", link: "/category/ac/service/repair-maintainance" , image: "Ac.jpg" },
    { id: "ac-coil-cleaning", value: "ac coil cleaning", link: "/category/ac/service/coil-cleaning" , image: "Ac.jpg" },
    { id: "ac-duct-cleaning", value: "ac duct cleaning", link: "/category/ac/service/duct-cleaning" , image: "Ac.jpg" },
    { id: "ac-installation", value: "ac installation", link: "/category/ac/service/installation" , image: "Ac.jpg" },
    // { id: "Off White/White", value: "Off White/White", link: "/category/painting/service/Off White/White" , image: "painting.jpg" },
    { id: "Color Painting", value: "Color Painting", link: "/category/painting/service/Color Painting" , image: "painting.jpg" },
    { id: " Water Damage Repair", value: " Water Damage Repair", link: "/category/painting/service/ Water Damage Repair" , image: "painting.jpg" },
    // { id: "Off White", value: "Off White", link: "/category/painting/service/Off-White" , image: "painting.jpg" },
    { id: "Off White", value: "Off White", link: "/category/painting/service/Off White" , image: "painting.jpg" },
    // { id: "interior-double-coat", value: "interior double coat", link: "/category/painting/service/interior-double-coat" , image: "painting.jpg" },
    // { id: "exterior-villa", value: "exterior villa", link: "/category/painting/service/exterior-villa" , image: "painting.jpg" },
    // { id: "room-painting", value: "room painting", link: "/category/painting/service/room-painting" , image: "painting.jpg" },
    // { id: "touchup-painting", value: "touchup painting", link: "/category/painting/service/touchup-painting" , image: "painting.jpg" },
    // { id: "custom-painting", value: "custom painting", link: "/category/painting/service/custom-painting" , image: "painting.jpg" },
    { id: "shutdown-repair", value: "shutdown repair", link: "/category/electrical/service/shutdown-repair" , image: "electrical.jpg" },
    { id: "fixture-or-repair", value: "fixture or repair", link: "/category/electrical/service/fixture-or-repair" , image: "electrical.jpg" },
    { id: "electrical-fitting", value: "electrical fitting", link: "/category/electrical/service/electrical-fitting" , image: "electrical.jpg" },
    { id: "power-switches-repair", value: "power switches repair", link: "/category/electrical/service/power-switches-repair" , image: "electrical.jpg" },
    { id: "large-fixture", value: "large fixture", link: "/category/plumbing/service/large-fixture" , image: "plumbing.jpg" },
    { id: "pipe-unclogging", value: "pipe unclogging", link: "/category/plumbing/service/pipe-unclogging" , image: "plumbing.jpg" },
    { id: "water-leakage", value: "water leakage", link: "/category/plumbing/service/water-leakage" , image: "plumbing.jpg" },
    { id: "water-overflow-repair", value: "water overflow repair", link: "/category/plumbing/service/water-overflow-repair" , image: "plumbing.jpg" },
    { id: "pump-or-motor-repair", value: "pump or motor repair", link: "/category/plumbing/service/pump-or-motor-repair" , image: "plumbing.jpg" },
    { id: "Kitchen", value: "Kitchen", link: "/category/deepcleaning/service/Kitchen" , image: "cleaning1.jpg"  },
    { id: "Bathroom", value: "Bathroom", link: "/category/deepcleaning/service/Bathroom" , image: "cleaning1.jpg"  },
    { id: "Balcony", value: "Balcony", link: "/category/deepcleaning/service/Balcony" , image: "cleaning1.jpg"  },
    { id: "Full Home", value: "Full Home", link: "/category/deepcleaning/service/full home" , image: "cleaning1.jpg"  },
    // { id: "curtain-cleaning", value: "curtain cleaning", link: "/category/deepcleaning/service/curtain-cleaning" , image: "cleaning1.jpg"  },
    { id: "Sofa cleaning", value: "Sofa cleaning", link: "/category/deepcleaning/service/sofa-cleaning" , image: "cleaning1.jpg"  },
    { id: "Add Ones", value: "Add Ones", link: "/category/deepcleaning/service/Add Ones" , image: "cleaning1.jpg"  },
    { id: "carpet-cleaning", value: "carpet cleaning", link: "/category/deepcleaning/service/carpet-cleaning" , image: "cleaning1.jpg"  },
    // { id: "drain-or-sewer-cleaning", value: "drain or sewer cleaning", link: "/category/deepcleaning/service/drain-or-sewer-cleaning" , image: "cleaning1.jpg"  },
    { id: "pruning-or-trimming", value: "garden pruning or trimming", link: "/category/gardening/service/pruning-or-trimming"  },
    { id: "sprinkler-or-drip-repair", value: "garden sprinkler or drip repair", link: "/category/gardening/service/sprinkler-or-drip-repair" },
    { id: "lawn-grass-carpeting", value: "lawn grass carpeting", link: "/category/gardening/service/lawn-grass-carpeting" },
    { id: "tree-or-stump-cutting", value: "tree or stump cutting", link: "/category/gardening/service/tree-or-stump-cutting" },
    { id: "sail-shade-installation", value: "sail shade installation", link: "/category/gardening/service/sail-shade-installation" },
    { id: "tree-or-flower-painting", value: "tree or flower painting", link: "/category/gardening/service/tree-or-flower-painting" },
    { id: "fake-grass-installation", value: "fake grass installation", link: "/category/gardening/service/fake-grass-installation" },
    { id: "garden-landscaping", value: "garden landscaping", link: "/category/gardening/service/garden-landscaping" },
    { id: "door-glass-replacement", value: "door glass replacement", link: "/category/glasswork/service/door-glass-replacement" ,image: "glass.jpg"  },
    { id: "window-glass-replacement", value: "window glass replacement", link: "/category/glasswork/service/window-glass-replacement" ,image: "glass.jpg"  },
    { id: "tabletop-glass-cutting", value: "tabletop glass slab cutting", link: "/category/glasswork/service/tabletop-glass-cutting" ,image: "glass.jpg"  },
    { id: "glass-partition-fabrication", value: "glass partition fabrication", link: "/category/glasswork/service/glass-partition-fabrication" ,image: "glass.jpg"  },
    { id: "bathroom-glass-fabrication", value: "bathroom glass fabrication", link: "/category/glasswork/service/bathroom-glass-fabrication" ,image: "glass.jpg"  },
    { id: "mirror-work", value: "mirror work", link: "/category/glasswork/service/mirror-work" ,image: "glass.jpg"  },
    { id: "glass-staircase-fabrication", value: "glass staircase fabrication", link: "/category/glasswork/service/glass-staircase-fabrication" ,image: "glass.jpg"  },
    { id: "glass-door-fabrication", value: "glass door fabrication", link: "/category/glasswork/service/glass-door-fabrication" ,image: "glass.jpg"  },
    { id: "door-window-glass-tint", value: "door and window glass tint", link: "/category/glasswork/service/door-window-glass-tint" ,image: "glass.jpg"  },
    { id: "custom-glass-job", value: "custom glass job", link: "/category/glasswork/service/custom-glass-job" , image: "glass.jpg"  },
    { id: "curtains-fixing", value: "curtains fixing", link: "/category/handyman/service/curtains-fixing" , image: "cleaning.jpg"  },
    { id: "flynet-screen-or-flynet-repair", value: "flynet screen or flynet repair", link: "/category/handyman/service/flynet-screen-or-flynet-repair" , image: "cleaning.jpg"  },
    { id: "chandelier-hanging", value: "chandelier hanging", link: "/category/handyman/service/chandelier-hanging" , image: "cleaning.jpg"  },
    { id: "decorative-lights-hanging", value: "decorative and festive lights hanging", link: "/category/handyman/service/decorative-lights-hanging" , image: "cleaning.jpg"  },
    { id: "modular-furniture-assembly", value: "modular furniture assembly", link: "/category/handyman/service/modular-furniture-assembly" , image: "cleaning.jpg" },
    { id: "wall-fixtures-hanging", value: "wall fixtures hanging", link: "/category/handyman/service/wall-fixtures-hanging" , image: "cleaning.jpg"  },
    { id: "lcd-tv-mounting", value: "lcd tv mounting", link: "/category/handyman/service/lcd-tv-mounting" , image: "cleaning.jpg"  },
    { id: "door-locks-repair", value: "door locks repair", link: "/category/handyman/service/door-locks-repair" , image: "cleaning.jpg"  },
    { id: "blinds-installation", value: "blinds installation", link: "/category/handyman/service/blinds-installation" , image: "cleaning.jpg"  },
    { id: "other-handyman-jobs", value: "other handyman jobs", link: "/category/handyman/service/other-handyman-jobs" , image: "cleaning.jpg"  },
    { id: "dishwasher-repair", value: "dishwasher repair", link: "/category/appliances/service/dishwasher-repair" },
    { id: "deep-freezer-repair", value: "deep freezer repair", link: "/category/appliances/service/deep-freezer-repair" },
    { id: "exhaust-fan-repair", value: "exhaust fan repair", link: "/category/appliances/service/exhaust-fan-repair" },
    { id: "cooking-range-repair", value: "cooking range or oven repair", link: "/category/appliances/service/cooking-range-repair" },
    { id: "extractor-hood-repair", value: "extractor hood repair", link: "/category/appliances/service/extractor-hood-repair" },
    { id: "washing-machine-or-dryer-repair", value: "washing machine or dryer repair", link: "/category/appliances/service/washing-machine-or-dryer-repair" },
    { id: "water-purifier-repair", value: "water purifier repair", link: "/category/appliances/service/water-purifier-repair" },
    { id: "fridge-repair", value: "fridge repair", link: "/category/appliances/service/fridge-repair" },
    { id: "water-dispenser-repair", value: "water dispenser repair", link: "/category/appliances/service/water-dispenser-repair" },
    { id: "microwave-repair", value: "microwave repair", link: "/category/appliances/service/microwave-repair" },
    { id: "appliance-installation", value: "appliance installation", link: "/category/appliances/service/appliance-installation" },
    { id: "custom-appliance-job", value: "custom appliance job", link: "/category/appliances/service/custom-appliance-job" },
    { id: "covid-sanitization", value: "covid sanitization", link: "/category/specialized/service/covid-sanitization" },
    { id: "wrap-innovative-renovations", value: "wrap innovative renovations", link: "/category/specialized/service/wrap-innovative-renovations" },
    { id: "grout-cleaning", value: "grout cleaning", link: "/category/specialized/service/grout-cleaning" },
    { id: "leather-restoration", value: "leather restoration", link: "/category/specialized/service/leather-restoration" }
]